### ISSUE TITLE
Roblox Developers Marketplace Prompt #1 [Hiring Prompt ONLY]

### ISSUE THREAD

**Issue by PineappleDoge** [Roblox-Developers-CodeSkids/RobloxDevelopers#2]
**-** On Init [RD;Post]
- Sends message in DMS [Message Below]

**Roblox Developers Marketplace Prompt**

Hello! You've successfully opted into the opting process. Please follow the prompt and answer appropriately and I'll post your hiring prompt to a secret moderation channel where『 M 』Moderators will review and either accept/decline your prompt. What are you looking to create a prompt for?

`Hiring` - Post a hiring request in any of the hiring channels! This doesn't include #portfolios or #selling.
`Selling` - Post a selling request in #selling! 
`Looking For Work` - Post your portfolio in #portfolios!

**-** On Failure Response [After RD;Post]

- Failure Message [You tried to post in a channel, but you don't meet the requirements]
Sorry, but you don't meet the requirements to post in this channel. You need Copper+, you have [role here]

**Comment by PineappleDoge** [comment]
**-** On Init [RD;Post]
- Sends message in DMS [Message Below]

**Roblox Developers Hiring Prompt**

Hello! You've successfully opted into the hiring process. To start, what channel(s) would you like to post your hiring ad in? After you have selected at least 1 channel you want to post in, press Y to continue the prompt. To remove a channel from the currently selected channels table, type "remove channel-name".

Current Selected Channel(s): No channels selected.

#builder-hiring, #modeler-hiring , #scripter-hiring, #animator-hiring, #clothing-hiring, #vfx-hiring, 
#graphics-hiring, #other-hiring





**-** On Failure Response [Didn't select a valid channel]

- Failure Message [Invalid Channel Type]
Sorry, but that's not a channel we support hiring request in. Please take a look above at what channels we support.





**-** On Failure Response [Channel that user tried to remove wasn't in the table]

- Failure Message [Invalid Channel Selecyion]
That channel isn't in your Current Select Channel(s) table. Remember, proper typing of the channel name is needed.

**Comment by PineappleDoge** [comment]
**-** On Hire (Continued) 
- Sends message in DMS [Message Below]

**Roblox Developers Hiring Prompt**

Great! Please type a description of the job you're looking for people to do. Be informative as possible, listing the workplace, stylistic visions, people on the team, ETC. 





**-** On Payment 
- Sends message in DMS [Message Below]

**Roblox Developers Hiring Prompt**

Great! Please list payment. If payment is negotiable, please list a price range in which you are willing to pay and **can** pay. If payment is percentage based (%), please state that. [EXX





**-** On Payment Failure [User didn't list a valid range]
- Sends message in DMS [Message Below]

**Roblox Developers Hiring Prompt**

That isn't a valid price range. Please type a valid price range that you can/are willing to pay.

**Comment by SovietKitsune** [comment]
Added at commit [6613fab](https://github.com/Roblox-Developers-CodeSkids/RobloxDevelopers/commit/6613fabaf6cee8c4f48d7bea565138e40aaf61a0).
