### ISSUE TITLE
Roblox Developers Selling Prompt

### ISSUE THREAD

**Issue by PineappleDoge** [Roblox-Developers-CodeSkids/RobloxDevelopers#4]
Continuation from Hiring Prompt, this path happens when you select "selling" after opening the post 

**Selling Text 1:**

> Great! Please attach an image containing a picture(s) about the product you wish to sell. The image will need to be in link form or uploaded directly to discord. If you'll like to skip this step, type next.

**Selling Text 2:**

> Write a short description about the product. This should list basic details about the product itself, who it's meant for, what it can/can't do, if it's going to be resold or not.

**Selling Text 3:**

> Please list a desired payment amount. Payment should be listed in a range from minimum accepted price to maximum accepted price. Payment numbers should end with the R$ Symbol (Robux), or another indicator of currency.

**Selling Text 4:**

> Please list correct contact info. Formats we support are listed below: 

```Discord :Emoji_Discord:   Twitter :Emoji_Twitter:   Email :Emoji_Gmail:```

Confirmation Selling Text:
Is this correct (y/yes, n/no)

`Order`
Selling Text 1 Result > Selling Text 4 Result > Selling Text 2 Result > Selling Text 3 Result

-------------------------------------------------------------------------------------

**Error Message 1 [Not a valid image]:**
That isn't a valid image link/image. To skip the image upload, you can text next.

**Error Message 2 [Not a valid payment]:**
That isn't a valid payment option. You'll need to include a payment/payment range for it to be valid.

**Error Message 3 [Not a valid discord tag]:**
That's isn't a valid discord tag. A valid discord tag should contain a username + tag [EX: PineappleDoge#2177]

**Error Message 4 [Not a valid twitter]:**
That isn't a valid twitter tag. A valid twitter tag should contain a username or link [EX: @PineappleDoggo1 or https://twitter.com/PineappleDoggo1]

**Error Message 5 [Not a valid email]:**
That isn't a valid email option. A valid email option should contain an email tag [EX: RandomEmail@gmail.com]

**Comment by SovietKitsune** [comment]
Shouldn't we have contact info for hiring as well?

**Comment by PineappleDoge** [comment]
Good idea, going to reopen hiring issue and add that in.

**Comment by SovietKitsune** [comment]
Completed in commit [6080c57](https://github.com/Roblox-Developers-CodeSkids/RobloxDevelopers/commit/6080c57a338f8462946d86f6cfd99321e44a1cda).
