### ISSUE TITLE
Roblox Developers Portfolio Prompt 

### ISSUE THREAD

**Issue by PineappleDoge** [Roblox-Developers-CodeSkids/RobloxDevelopers#6]
Continuation from `Post command, this happens when you select "Looking For Work".

**Looking For Work Text 1**
> Awesome, you're looking to post your work and show off your stuff. Do you perhaps have a website or a place that you have all your work in? If not, type _next_ to skip this portion. [EX: Devforums Portfolio, Artstation Portfolio, Custom Website]

**Looking For Work Text 2**
> Alright, can you give a short title for your portfolio post? [EX: UsernameHere | Builder, Scripter, Animator] 

**Looking For Work Text 3**
> Great! Can you give a short description about yourself and what you do? 

**Looking For Work Text 4**
> Please send examples of your work, they'll need to be in link format or uploaded to Discord directly. Once you finish uploading your examples, type next to continue. Note: Only your first link will embed, and we have a mix limit of 3.

Current Links/Examples of work: 

**Looking For Work Text 5**
> Final step, list your preferred contacts. Currently supported contact info is listed below: 

:Emoji_Discord: Discord  |  :Emoji_Twitter: Twitter  |  :Emoji_Gmail: Email 

**Confirmation Text**
Does this look right to you? [y/yes, n/no]

Display Format: Text 2 [Header] -> Text 4 -> Text 3 -> Text 1 -> Text 5

-------------------------------------------------------------------------------------

Error Message 1 [No Proper Links/Images/Gifs]
* Whoops! You posted a invalid media type. We only support GIFS, Images, and Links. 

Error Message 2 [Too many links/max link limit]
* Whoops! You reached the max link limit. You can remove a link by typing `remove 1`. [Link Array: Link 1, Link 2, Link 3] [EX: remove 1, remove 2, remove 3]

Error Message 3 [Invalid Contact Info]
* We don't support that contact info. We currently support twitter, email, and discord

Default Error Message 
* Sorry, but that doesn't work. Can you try again?

**Comment by SovietKitsune** [comment]
Should I put a captcha on marketplace posts?

**Comment by SovietKitsune** [comment]
Completed in commit [6080c57](https://github.com/Roblox-Developers-CodeSkids/RobloxDevelopers/commit/6080c57a338f8462946d86f6cfd99321e44a1cda).
